services:
  copilot-frontend:
    build:
      context: .
      args:
        - VITE_YANDEX_API_KEY
        - VITE_YANDEX_FOLDER_ID
    container_name: copilot-frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
    name: remnawave-network
